# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
