# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0004_auto_20180201_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=1, help_text='Количество товара', verbose_name='Количество'),
        ),
    ]
