# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0005_auto_20180203_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchased',
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=0, help_text='Товар куплен?', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
