# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0006_auto_20180203_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.PositiveIntegerField(verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='value',
            field=models.SmallIntegerField(verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Название'),
        ),
    ]
