# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0007_auto_20180204_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритет'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Ед. измерения', 'verbose_name_plural': 'Ед. измерения'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=False, help_text='Товар куплен?', verbose_name='Статус'),
        ),
    ]
