# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0008_auto_20180206_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='value',
        ),
    ]
