# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0009_auto_20180206_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(help_text='Название товара', max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
